### ISSUE TITLE
Missing required modules in stix shifter/basic_df_analysis notebook

### ISSUE THREAD

**Issue by JasonKeirstead** [IBM/ibm-security-notebooks#10]
Missing the following dependency modules when running 

from pyclient.stix_shifter_dataframe import StixShifterDataFrame

!pip install pandas
!pip install anytree
from pyclient.stix_shifter_dataframe import StixShifterDataFrame

Not sure if dependancies are an issue or what.

**Comment by charliewutw1** [comment]
We need to put these libraries in pyclient's requirement.txt, and this will be fixed in next PR.
